"""add user_favorite_players table

Revision ID: 0b02cea5525f
Revises: 23445855672f
Create Date: 2025-05-15 17:47:02.951699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b02cea5525f'
down_revision: Union[str, None] = '23445855672f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_user_team',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_api_player', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_api_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_user_team')
    # ### end Alembic commands ###
