"""fix user_favorite_players table

Revision ID: 0cfa5de9cd60
Revises: 02aed1995498
Create Date: 2025-05-18 15:13:23.889246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfa5de9cd60'
down_revision: Union[str, None] = '02aed1995498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorite_user_player', 'base_players', ['id_api_player'], ['api_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_user_player', type_='foreignkey')
    # ### end Alembic commands ###
