"""add user_favorite_players table

Revision ID: 133a6d66681c
Revises: c805bb8bf8ec
Create Date: 2025-05-15 17:42:03.580412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133a6d66681c'
down_revision: Union[str, None] = 'c805bb8bf8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_user_league', sa.Column('id_api_league', sa.Integer(), nullable=False))
    op.drop_constraint('favorite_user_league_id_league_fkey', 'favorite_user_league', type_='foreignkey')
    op.drop_column('favorite_user_league', 'id_league')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_user_league', sa.Column('id_league', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('favorite_user_league_id_league_fkey', 'favorite_user_league', 'leagues', ['id_league'], ['id'])
    op.drop_column('favorite_user_league', 'id_api_league')
    # ### end Alembic commands ###
