"""Renomear dribbles_completed para dribbles_past e remover formation_grid

Revision ID: 179bc5c4afab
Revises: b2e90bfa4a7a
Create Date: 2025-05-05 23:26:08.363550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179bc5c4afab'
down_revision: Union[str, None] = 'b2e90bfa4a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture_player_stats', sa.Column('dribbles_past', sa.SmallInteger(), nullable=True))
    op.drop_column('fixture_player_stats', 'dribbles_completed')
    op.drop_column('fixture_player_stats', 'formation_grid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture_player_stats', sa.Column('formation_grid', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('fixture_player_stats', sa.Column('dribbles_completed', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('fixture_player_stats', 'dribbles_past')
    # ### end Alembic commands ###
