"""Add grid column to FixturePlayerStat

Revision ID: 36f7a6e5877d
Revises: 8b4b99753eab
Create Date: 2025-06-16 14:51:21.795675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f7a6e5877d'
down_revision: Union[str, None] = '8b4b99753eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture_player_stats', sa.Column('grid', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixture_player_stats', 'grid')
    # ### end Alembic commands ###
