"""Create TeamSeasonStat table

Revision ID: 88c1fdff0986
Revises: 966962792894
Create Date: 2025-06-17 16:00:36.158218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c1fdff0986'
down_revision: Union[str, None] = '966962792894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_team_id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=True, comment='Ex: WDWLDWLDLDW...'),
    sa.Column('fixtures_played', sa.SmallInteger(), nullable=True),
    sa.Column('fixtures_wins', sa.SmallInteger(), nullable=True),
    sa.Column('fixtures_draws', sa.SmallInteger(), nullable=True),
    sa.Column('fixtures_loses', sa.SmallInteger(), nullable=True),
    sa.Column('biggest_streak_wins', sa.SmallInteger(), nullable=True),
    sa.Column('biggest_streak_draws', sa.SmallInteger(), nullable=True),
    sa.Column('biggest_streak_loses', sa.SmallInteger(), nullable=True),
    sa.Column('biggest_win', sa.String(length=10), nullable=True),
    sa.Column('biggest_loss', sa.String(length=10), nullable=True),
    sa.Column('clean_sheets', sa.SmallInteger(), nullable=True),
    sa.Column('failed_to_score', sa.SmallInteger(), nullable=True),
    sa.Column('penalty_scored', sa.SmallInteger(), nullable=True),
    sa.Column('penalty_missed', sa.SmallInteger(), nullable=True),
    sa.Column('penalty_total', sa.SmallInteger(), nullable=True),
    sa.Column('lineups', sa.JSON(), nullable=True, comment='Lista de escalações e quantas vezes foi usada'),
    sa.Column('cards_by_minute', sa.JSON(), nullable=True, comment='Objeto de cartões por intervalo de minutos'),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_team_id'], ['league_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_season_stats_id'), 'team_season_stats', ['id'], unique=False)
    op.create_index(op.f('ix_team_season_stats_league_team_id'), 'team_season_stats', ['league_team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_season_stats_league_team_id'), table_name='team_season_stats')
    op.drop_index(op.f('ix_team_season_stats_id'), table_name='team_season_stats')
    op.drop_table('team_season_stats')
    # ### end Alembic commands ###
