"""Remove game_position and add rating to FixturePlayerStat

Revision ID: 8b4b99753eab
Revises: b93a86009a7f
Create Date: 2025-06-09 14:33:02.338888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4b99753eab'
down_revision: Union[str, None] = 'b93a86009a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture_player_stats', sa.Column('rating', sa.DECIMAL(precision=4, scale=2), nullable=True))
    op.drop_column('fixture_player_stats', 'game_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture_player_stats', sa.Column('game_position', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.drop_column('fixture_player_stats', 'rating')
    # ### end Alembic commands ###
