"""Create TeamSeasonStat table

Revision ID: 985ed43ec0ab
Revises: 88c1fdff0986
Create Date: 2025-06-17 16:34:05.797106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985ed43ec0ab'
down_revision: Union[str, None] = '88c1fdff0986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_season_stats', 'biggest_win',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'biggest_loss',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_season_stats', 'biggest_loss',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('team_season_stats', 'biggest_win',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
