"""add expected_goals to fixture_statistics

Revision ID: b2e90bfa4a7a
Revises: ed69c68665ce
Create Date: 2025-05-05 14:12:33.091375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e90bfa4a7a'
down_revision: Union[str, None] = 'ed69c68665ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture_statistics', sa.Column('expected_goals', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixture_statistics', 'expected_goals')
    # ### end Alembic commands ###
