"""Adicionar relacionamentos inversos para fixture_events

Revision ID: c926022c088e
Revises: e63ac09cd8f5
Create Date: 2025-04-28 12:03:48.898880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c926022c088e'
down_revision: Union[str, None] = 'e63ac09cd8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_api_id', sa.Integer(), nullable=False),
    sa.Column('team_api_id', sa.Integer(), nullable=False),
    sa.Column('player_api_id', sa.Integer(), nullable=True),
    sa.Column('assist_player_api_id', sa.Integer(), nullable=True),
    sa.Column('time_elapsed', sa.Integer(), nullable=False),
    sa.Column('time_extra', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.String(length=100), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assist_player_api_id'], ['base_players.api_id'], ),
    sa.ForeignKeyConstraint(['fixture_api_id'], ['fixtures.api_id'], ),
    sa.ForeignKeyConstraint(['player_api_id'], ['base_players.api_id'], ),
    sa.ForeignKeyConstraint(['team_api_id'], ['base_teams.api_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixture_events_id'), 'fixture_events', ['id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_fixture_events_id'), table_name='fixture_events')
    op.drop_table('fixture_events')
    # ### end Alembic commands ###
