"""Adiciona colunas de Elo na tabela Fixture

Revision ID: e4e44098df65
Revises: 985ed43ec0ab
Create Date: 2025-09-01 15:13:02.853699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e44098df65'
down_revision: Union[str, None] = '985ed43ec0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('home_team_elo_before', sa.Float(), nullable=True))
    op.add_column('fixtures', sa.Column('away_team_elo_before', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixtures', 'away_team_elo_before')
    op.drop_column('fixtures', 'home_team_elo_before')
    # ### end Alembic commands ###
