"""add user_favorite_players table

Revision ID: f780e9e0a6ee
Revises: 0b02cea5525f
Create Date: 2025-05-15 17:48:34.301948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f780e9e0a6ee'
down_revision: Union[str, None] = '0b02cea5525f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_user_player',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_api_player', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_api_player')
    )
    op.drop_table('favorite_user_team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_user_team',
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_api_player', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name='favorite_user_team_id_user_fkey'),
    sa.PrimaryKeyConstraint('id_user', 'id_api_player', name='favorite_user_team_pkey')
    )
    op.drop_table('favorite_user_player')
    # ### end Alembic commands ###
